=== vandalieu06/programacion/xml/RA1/act03/restaurante.dtd
<!-- Definim el element pare i aquest tindra un o mes elements anomenats soapr -->
<!ELEMENT restaurant (sopar+)>

<!-- Definim el element sopar i aquest contindra tres elements -->
  <!ELEMENT sopar (taula, plats, total)>

<!--  Definim el element taula i aquest contindra un element anomenat comensal -->
    <!ELEMENT taula (#PCDATA)>

<!-- Definim un element anomenat plats i diem que aquest contindra 1 o mes elements anomenats plat -->
    <!ELEMENT plats (plat+)>

<!-- Definim el element anomenat plat i aquest contindra els elements anomenats nom, preu i ingredients -->
      <!ELEMENT plat (nom, preu, ingredients)>

<!-- Definim que el element nom i aquest contindra text per que hem definit (#PCDATA) -->
        <!ELEMENT nom (#PCDATA)>

<!-- Definim que el element preu i aquest contindra text per que hem definit (#PCDATA) -->
        <!ELEMENT preu (#PCDATA)>

<!-- Definim que el element ingredients que contindra un o mes elements anomenat ingredient -->
        <!ELEMENT ingredients (ingredient+)>

<!-- Definim que el element ingredient contindra text -->
          <!ELEMENT ingredient (#PCDATA)>

<!-- Definim el element total contindra text -->
    <!ELEMENT total (#PCDATA)>

<!--  Definim que taula tindra un atrbut anomenta comensals -->

<!--  La taula tindra un atribut que es posaran el nombre comensals que hi han a la taula-->
<!ATTLIST sopar id ID #REQUIRED>

<!--  La taula tindra un atribut que es posaran el nombre comensals que hi han a la taula-->
<!ATTLIST taula comensals CDATA #IMPLIED>

<!--  Els plats tindran un atribut anomenat id per identificar a cada plat del restaurant-->
<!ATTLIST plat codi-plat CDATA #REQUIRED>

=== vandalieu06/programacion/xml/act03/restaurante.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurant SYSTEM "restaurante.dtd">

<restaurant>
  <sopar id="S001">
    <taula comensals="4"/>
    <plats>
      <plat codi-plat="P001">
        <nom>Paella de marisc</nom>
        <preu>20.00</preu>
        <ingredients>
          <ingredient>Arr√≤s</ingredient>
          <ingredient>Marisc</ingredient>
          <ingredient>All</ingredient>
          <ingredient>Oli d'oliva</ingredient>
        </ingredients>
      </plat>
      
      <plat codi-plat="P002" >
        <nom>Crema catalana</nom>
        <preu>6.00</preu>
        <ingredients>
          <ingredient>Llet</ingredient>
          <ingredient>Sucre</ingredient>
          <ingredient>Ous</ingredient>
          <ingredient>Canella</ingredient>
        </ingredients>
      </plat>
    </plats>
    <total>26.00</total>
  </sopar>
</restaurant>
