=== vandalieu06/programacion/xml/RA2/ACT06/client.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="clients">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="client" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="apellidos" type="xs:string"/>
              <xs:element name="telf" type="xs:int"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="direccion" maxOccurs="unbounded"> 
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="calle" type="xs:string"/>
                    <xs:element name="numero" type="xs:int"/>
                    <xs:element name="codigo-postal" type="xs:int"/>
                    <xs:element name="ciudad" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vandalieu06/programacion/xml/RA2/ACT06/client.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./client.xsd">
 <client>
  <nombre>Juan</nombre>
  <apellidos>Pérez González</apellidos>
  <telf>999666333</telf>
  <email>email@google.com</email>
  <direccion>
    <calle>Carrer de Nadal</calle>
    <numero>57</numero>
    <codigo-postal>08204</codigo-postal>
    <ciudad>Sabadell</ciudad>
  </direccion>
 </client>
 
 <client>
  <nombre>Maria</nombre>
  <apellidos>Ruiz Martínez</apellidos>
  <telf>999666333</telf>
  <email>email@google.com</email>
  <direccion>
    <calle>Carretera Barcelona</calle>
    <numero>103</numero>
    <codigo-postal>08205</codigo-postal>
    <ciudad>Sabadell</ciudad>
  </direccion>
 </client>
</clients>
