=== vandalieu06/programacion/xml/act04/departaments.dtd
<!ELEMENT llistacompra (venda+)>
<!ELEMENT venda (vendacredit | vendainmediat)>
<!ELEMENT vendacredit (datafipagament?, quantitat)>
<!ELEMENT vendainmediat (quantitat, divisa)>
<!ELEMENT datafipagament (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT divisa (#PCDATA)>

<!ATTLIST venda id ID #REQUIRED>

=== vandalieu06/programacion/xml/act04/departaments.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistacompra SYSTEM "departaments.dtd">

<llistacompra>
  <venda id="V001">
    <vendacredit>
      <datafipagament>2024-10-14</datafipagament>
      <quantitat>10</quantitat>
    </vendacredit>
  </venda>
  <venda id="V002">
    <vendainmediat>
      <quantitat>10</quantitat>
      <divisa>10</divisa>
    </vendainmediat>
  </venda>
</llistacompra>
